### ISSUE TITLE
jspm config endpoint now registry

### ISSUE THREAD

**Issue by edrex** [djindjic/generator-jspm-lib#2]
https://github.com/jspm/github/commit/a5dbaeee9 changed 

```
jspm endpoint config github
```

to

```
jspm registry config github
```

and moved the auth key from `endpoints.github.auth` to `registries.github.auth`.

This is simple enough that I started to fix it myself but then realized that I was falling asleep so wanted to file an issue lest I forget about it. :beers:

**Comment by djindjic** [comment]
Hey thanks! I have just updated it in readme and [travis.yml](https://github.com/djindjic/generator-jspm-lib/blob/e1c9106c65e565f58e209dc951365868a9cca5db/app/templates/travis.yml#L9)
