### ISSUE TITLE
babel?

### ISSUE THREAD

**Issue by edrex** [djindjic/generator-jspm-lib#4]
I've been using Babel rather than Traceur with System.js, since that seems to be considered a better option by folks who have seriously evaluated them.

Alternate proposals:
- Switch to Babel (just a few lines)
- Add a prompt to the configurator like `jspm init`

**Comment by djindjic** [comment]
Yes, I agree, we could switch this to babel transpiling

**Comment by edrex** [comment]
Thanks! The generated `config.js` still has `"transpiler": "traceur"`. There doesn't seem to be a non-interactive way to tell `jspm init/install` to use babel. I'll ask upstream.

**Comment by edrex** [comment]
Some options:
- Put `config.js` in the generator
- Use something like [nexpect](https://www.npmjs.com/package/nexpect) to interact with `jspm install`, sin `-y`
- Doesn't [look like](https://github.com/jspm/jspm-cli/blob/master/lib/config.js) jspm-cli has a public api for creating `config.js`

**Comment by djindjic** [comment]
Oh yes, I added config.js with babel flag into template. I hope it's ok now.
I'm not sure about api support for jspm init but babel is so much better option and it doesn't worth to try implementing transpiler chooser in this case.

**Comment by edrex** [comment]
:+1: looks good to me
